Gsa/staging/production release
GSA/smartpay-training pull request #458
Opened 2023-12-05 15:20 UTC by felder101

2023-12-06 22:55 UTC, mark-meyer requested changes
Most of this looks great to me. 

I think we need to be a little more rigorous with a couple of the tests. I've added comments in the code. It's primarily making sure we are really covering the new functionality with tests. As it is, the tests will still pass even if we disable the new functionality around emailing certificates. I'd be happy to pair up if you want to bang through any of this together.

2023-12-06 22:55 UTC, mark-meyer commented on training/services/quiz.py
> +    def email_certificate(self, user_name: str, course_name: str, to_email: str, certificate: bytes) -> None:
We are not covering the new `email_certificate()` function with any tests.  You can remove all functionality from this method and tests still pass. Unless there's a good reason not to, we should be covering this in a unit test. The coverage on this file went from 97% to 74%. We don't need to be overly rigid with testing, but this seems like a step in the wrong direction.

2023-12-06 22:55 UTC, mark-meyer commented on training/tests/test_quiz_service.py
> +@patch.object(Certificate, "generate_pdf")
We don't _need_ to mock the pdf generation. Since generating the pdfs doesn't reach out to an external source of hit an API, my hunch is that we should let the real function run unless we wanted to make assertions against it (which you might).

2023-12-13 15:28 UTC, felder101 commented on training/services/quiz.py
> +    def email_certificate(self, user_name: str, course_name: str, to_email: str, certificate: bytes) -> None:
This will be refactored with a future story. With more mechanisms to send more emails through the application I believe a email service will be needed, which will avoid having similar code throughout the application.

Added new unit test method to test email_certificate() method. The file coverage is now at 97%.

2023-12-13 15:33 UTC, felder101 commented on training/tests/test_quiz_service.py
>  def test_grade_passing(
Unit test method has been updated to test new code added.

2023-12-13 15:48 UTC, mark-meyer approved these changes
Looks good to me!

2023-12-13 20:29 UTC, merged