Feature/19 gspc admin page
GSA/smartpay-training pull request #505
Opened 2024-03-05 20:29 UTC by john-labbate

2024-03-06 16:53 UTC, felder101 requested changes

2024-03-06 16:53 UTC, felder101 commented on .env_example
> +BASE_URL="http://localhost:3000"
Believe this can be reverted as it list to update in the deploy instructions in the readme.

2024-03-06 16:53 UTC, felder101 commented on training-front-end/src/pages/admin/index.astro
> +        <!-- <li class="usa-card tablet:grid-col-6">
Should this be commented out? How will the admin access the page?

2024-03-06 16:53 UTC, felder101 commented on training/api/api_v1/gspc.py
> +    user=Depends(RequireRole(["Admin"]))
I think you are missing the Authorization header in the request on the vue component. Can you check to see if the  user authorization is happening?

2024-03-06 16:53 UTC, felder101 commented on training/schemas/gspc_invite.py
> +    # def __init__(self, email_addresses, certification_expiration_date):
Please remove commented out code.

2024-03-06 17:39 UTC, john-labbate commented on training-front-end/src/pages/admin/index.astro
> +        <!-- <li class="usa-card tablet:grid-col-6">
They want it removed for this deployment

2024-03-06 18:33 UTC, john-labbate commented on .env_example
> +BASE_URL="http://localhost:3000"
Reverted

2024-03-06 18:34 UTC, john-labbate commented on training/api/api_v1/gspc.py
> +    user=Depends(RequireRole(["Admin"]))
Added, nice spot. I still need dataset for my local to get the admin role

2024-03-06 18:34 UTC, john-labbate commented on training/schemas/gspc_invite.py
> +    # def __init__(self, email_addresses, certification_expiration_date):
removed

2024-03-07 14:06 UTC, felder101 approved these changes

2024-03-07 14:09 UTC, merged